// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3219.ButtercupIV;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Talon;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static Talon leftDrive;
    public static Talon rightDrive;
    public static Solenoid rightCannon;
    public static Solenoid leftCannon;
    public static Solenoid airHorn;

    public static void init() {
    	//motors
    	rightDrive = new Talon(0);
    	leftDrive = new Talon(1);
    	//pnumatics
    	rightCannon = new Solenoid(0);
    	leftCannon = new Solenoid(1);
    	airHorn = new Solenoid(2);
    }
}
